# Generated by Django 4.2.14 on 2024-09-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digilab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testavailable',
            name='lab_personnel',
        ),
    ]
