# Generated by Django 4.2.14 on 2024-10-01 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digilab', '0002_remove_testavailable_lab_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LpProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('license_upload', models.FileField(blank=True, null=True, upload_to='licenses/')),
                ('certificate_upload', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lab Personnel',
            },
        ),
    ]
