# Generated by Django 4.2.14 on 2024-10-02 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digilab', '0003_lpprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LpProfile',
            new_name='LabPersonnelProfile',
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('test_description', models.TextField()),
                ('test_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('assigned_lab_personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tests', to='digilab.labpersonnel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='digilab.patient')),
            ],
        ),
        migrations.CreateModel(
            name='OngoingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ongoing_test', to='digilab.test')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completed_test', to='digilab.test')),
            ],
        ),
    ]
