# Generated by Django 4.2.14 on 2024-10-02 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digilab', '0004_rename_lpprofile_labpersonnelprofile_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=255)),
                ('test_details', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digilab.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_paid', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digilab.test')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_code', models.CharField(max_length=255)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digilab.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(help_text='Enter the medical condition', max_length=255)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, help_text='List medications taken for this condition', null=True)),
                ('allergies', models.TextField(blank=True, help_text='List any known allergies', null=True)),
                ('treatments', models.TextField(blank=True, help_text='Describe past treatments, surgeries, or therapy', null=True)),
                ('doctor_notes', models.TextField(blank=True, help_text='Any additional notes from the doctor', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='digilab.patient')),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('broadcasted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lab_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digilab.labpersonnel')),
            ],
        ),
    ]
